apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-deployment
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-deployment
    spec:
      containers:
      - image: mongo:6.0.3
        name: mongo
        resources: {}
status: {}
